// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLYyJL1O3Cy7ruUQeDTe-yHpyFNkHaeh0',
    appId: '1:855501853687:web:faeb58e731c0f87d8c54f2',
    messagingSenderId: '855501853687',
    projectId: 'flutterfirebase-64100',
    authDomain: 'flutterfirebase-64100.firebaseapp.com',
    storageBucket: 'flutterfirebase-64100.appspot.com',
    measurementId: 'G-LG9E4EF9V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6SISKaWSxy5f8-UNmg1W2r16feYlr28',
    appId: '1:855501853687:android:d7ec6b8215a0e4b88c54f2',
    messagingSenderId: '855501853687',
    projectId: 'flutterfirebase-64100',
    storageBucket: 'flutterfirebase-64100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDASbbww9UoBOIeHjpsJz87m1DW208s3FA',
    appId: '1:855501853687:ios:ece86f7d4072e5bb8c54f2',
    messagingSenderId: '855501853687',
    projectId: 'flutterfirebase-64100',
    storageBucket: 'flutterfirebase-64100.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

}